import os
import logging
import smtplib
import urllib.parse
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

logger = logging.getLogger(__name__)


def generate_mailto_link(lead_data: dict) -> str:
    """Generate a mailto link for client-side email submission."""
    to_email = os.getenv("LEAD_TO_EMAIL", "miamilovesgreenlandscaping@gmail.com")
    subject = f"🚀 New Quote Lead: {lead_data.get('name')}"

    body = f"""
New Lead Capture Details:
-------------------------
Timestamp: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Name: {lead_data.get("name")}
Email: {lead_data.get("email")}
Phone: {lead_data.get("phone")}
Description: {lead_data.get("description")}

-------------------------
Generated by Miami Loves Green Landscaping Chatbot
"""

    # URL encode the parameters
    params = {"subject": subject, "body": body}
    query_string = urllib.parse.urlencode(params)

    return f"mailto:{to_email}?{query_string}"


def send_lead_email(lead_data: dict) -> bool:
    """
    Send lead details via SMTP email.
    Uses environment variables for configuration with hardcoded fallbacks.
    """
    # Hardcoded fallbacks for Miami Loves Green
    smtp_host = os.getenv("SMTP_HOST") or "smtp.gmail.com"
    smtp_port = os.getenv("SMTP_PORT") or "587"
    smtp_user = os.getenv("SMTP_USER") or "miamilovesgreenlandscaping@gmail.com"
    smtp_pass = os.getenv("SMTP_PASS") or "zcmhxmzfypdcvhrp"
    lead_to = os.getenv("LEAD_TO_EMAIL") or "miamilovesgreenlandscaping@gmail.com"

    if not all([smtp_host, smtp_user, smtp_pass, lead_to]):
        logger.error("❌ Email failed: Missing SMTP configuration.")
        return False

    try:
        # Create message
        msg = MIMEMultipart()
        msg["From"] = smtp_user
        msg["To"] = lead_to
        msg["Subject"] = f"🚀 New Lead: {lead_data.get('name')} - Miami Loves Green"

        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        body = f"""
        <h2>New Landscaping Lead Captured</h2>
        <p>A new lead has been captured via the Miami Loves Green Chatbot.</p>
        <hr>
        <p><strong>Timestamp:</strong> {timestamp}</p>
        <p><strong>Name:</strong> {lead_data.get("name")}</p>
        <p><strong>Email:</strong> {lead_data.get("email")}</p>
        <p><strong>Phone:</strong> {lead_data.get("phone", "Not provided")}</p>
        <p><strong>Project Description:</strong><br>{lead_data.get("description")}</p>
        <hr>
        <p><small>This is an automated message from your AI Assistant.</small></p>
        """

        msg.attach(MIMEText(body, "html"))

        # Connect and send
        server = smtplib.SMTP(smtp_host, int(smtp_port))
        server.starttls()
        server.login(smtp_user, smtp_pass)
        server.send_message(msg)
        server.quit()

        logger.info(f"✅ Lead email sent successfully to {lead_to}")
        return True

    except Exception as e:
        logger.error(f"❌ Failed to send lead email: {e}")
        return False


def check_email_config() -> bool:
    """Verify if email configuration is present."""
    return all(
        [
            os.getenv("SMTP_HOST"),
            os.getenv("SMTP_PORT"),
            os.getenv("SMTP_USER"),
            os.getenv("SMTP_PASS"),
            os.getenv("LEAD_TO_EMAIL"),
        ]
    )
