import os
import logging
import smtplib
import urllib.parse
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

logger = logging.getLogger(__name__)


def generate_mailto_link(lead_data: dict) -> str:
    """Generate a mailto link for client-side email submission."""
    to_email = os.getenv("LEAD_TO_EMAIL", "futureai4all@gmail.com")
    subject = f"🚀 New Project Inquiry: {lead_data.get('name')}"

    body = f"""
New Project Inquiry Details:
-------------------------
Timestamp: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Name: {lead_data.get("name")}
Email: {lead_data.get("email")}
Phone: {lead_data.get("phone")}
Description: {lead_data.get("description")}

-------------------------
Generated by Pinnacle AI Expert Chatbot
"""

    # URL encode the parameters
    params = {"subject": subject, "body": body}
    query_string = urllib.parse.urlencode(params)

    return f"mailto:{to_email}?{query_string}"


def send_lead_email(lead_data: dict) -> bool:
    """
    Send lead details via SMTP email.
    Uses environment variables for configuration with hardcoded fallbacks.
    """
    # Hardcoded fallbacks for Pinnacle AI Expert Notifications
    smtp_host = os.getenv("SMTP_HOST") or "smtp.gmail.com"
    smtp_port = os.getenv("SMTP_PORT") or "587"
    smtp_user = os.getenv("SMTP_USER") or "futureai4all@gmail.com"
    smtp_pass = os.getenv("SMTP_PASS") or "zcmhxmzfypdcvhrp"
    lead_to = os.getenv("LEAD_TO_EMAIL") or "futureai4all@gmail.com"

    if not all([smtp_host, smtp_user, smtp_pass, lead_to]):
        logger.error("❌ Email failed: Missing SMTP configuration.")
        return False

    try:
        # Create message
        msg = MIMEMultipart()
        msg["From"] = smtp_user
        msg["To"] = lead_to
        msg["Subject"] = f"🚀 New Project: {lead_data.get('name')} - Pinnacle AI"

        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        body = f"""
        <h2>New Project Inquiry Captured</h2>
        <p>A new inquiry has been captured via the Pinnacle AI Expert Chatbot.</p>
        <hr>
        <p><strong>Timestamp:</strong> {timestamp}</p>
        <p><strong>Name:</strong> {lead_data.get("name")}</p>
        <p><strong>Email:</strong> {lead_data.get("email")}</p>
        <p><strong>Phone:</strong> {lead_data.get("phone", "Not provided")}</p>
        <p><strong>Project Description:</strong><br>{lead_data.get("description")}</p>
        <hr>
        <p><small>This is an automated message from the Pinnacle AI Expert Systems.</small></p>
        """

        msg.attach(MIMEText(body, "html"))

        # Connect and send with enhanced diagnostics
        logger.info(f"Connecting to SMTP host {smtp_host}:{smtp_port}...")
        server = smtplib.SMTP(smtp_host, int(smtp_port), timeout=15)
        
        logger.info("Starting TLS...")
        server.starttls()
        
        logger.info(f"Attempting SMTP login for {smtp_user}...")
        server.login(smtp_user, smtp_pass)
        
        logger.info(f"Sending message to {lead_to}...")
        server.send_message(msg)
        
        server.quit()
        logger.info(f"✅ Lead email sent successfully to {lead_to}")
        return True

    except smtplib.SMTPAuthenticationError:
        logger.error(f"❌ SMTP AUTH FAILED: Check credentials for {smtp_user}")
        return False
    except smtplib.SMTPConnectError:
        logger.error(f"❌ SMTP CONNECTION FAILED: Could not connect to {smtp_host}")
        return False
    except Exception as e:
        logger.error(f"❌ SMTP Error: {type(e).__name__}: {e}", exc_info=True)
        return False


def check_email_config() -> bool:
    """Verify if email configuration is present."""
    return all(
        [
            os.getenv("SMTP_HOST"),
            os.getenv("SMTP_PORT"),
            os.getenv("SMTP_USER"),
            os.getenv("SMTP_PASS"),
            os.getenv("LEAD_TO_EMAIL"),
        ]
    )
